package com.dseme.app.dtos.meofficer;

import com.dseme.app.enums.ReportType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * DTO for report document metadata.
 * Used for managing repository of generated documents.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ReportDocumentDTO {
    /**
     * Document ID (ReportSnapshot ID).
     */
    private UUID documentId;
    
    /**
     * Report name (e.g., "Monthly Progress Report").
     */
    private String reportName;
    
    /**
     * Report type (MONTHLY, QUARTERLY, ANNUAL, CUSTOM).
     */
    private ReportType reportType;
    
    /**
     * Period (e.g., "Jan 2024" or date range).
     */
    private String period;
    
    /**
     * Period start date.
     */
    private LocalDate periodStart;
    
    /**
     * Period end date.
     */
    private LocalDate periodEnd;
    
    /**
     * File size as formatted string (e.g., "2.4 MB").
     */
    private String fileSize;
    
    /**
     * File size in bytes.
     */
    private Long fileSizeBytes;
    
    /**
     * File format (CSV, PDF, JSON).
     */
    private String fileFormat;
    
    /**
     * Download URL or endpoint to trigger blob stream.
     */
    private String downloadUrl;
    
    /**
     * Generated by (user name).
     */
    private String generatedByName;
    
    /**
     * Generated at timestamp.
     */
    private Instant generatedAt;
}
