package com.dseme.app.services.donor;

import com.dseme.app.dtos.donor.DonorContext;
import com.dseme.app.dtos.donor.ExportReportRequestDTO;
import com.dseme.app.models.Partner;
import com.dseme.app.models.ReportSnapshot;
import com.dseme.app.repositories.PartnerRepository;
import com.dseme.app.repositories.ReportSnapshotRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Service for DONOR report generation and export.
 * 
 * Provides:
 * - Portfolio-wide aggregated reports
 * - CSV and PDF export formats
 * - Branding-ready reports
 * - Async-safe for large datasets
 */
@Slf4j
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class DonorReportService {

    private final DonorAnalyticsService analyticsService;
    private final PartnerRepository partnerRepository;
    private final ReportSnapshotRepository reportSnapshotRepository;

    /**
     * Exports portfolio-wide report in CSV or PDF format.
     * 
     * @param context DONOR context
     * @param request Export request with report type and format
     * @return Report data as byte array
     * @throws IOException if export fails
     */
    public byte[] exportReport(DonorContext context, ExportReportRequestDTO request) throws IOException {
        String reportType = request.getReportType() != null ? 
                request.getReportType().toUpperCase() : "COMPREHENSIVE";
        String format = request.getFormat() != null ? 
                request.getFormat().toUpperCase() : "CSV";

        // Generate report data (CSV format internally)
        byte[] csvData = switch (reportType) {
            case "ENROLLMENT" -> exportEnrollmentReport(context, request);
            case "EMPLOYMENT" -> exportEmploymentReport(context, request);
            case "DEMOGRAPHIC" -> exportDemographicReport(context, request);
            case "COMPREHENSIVE" -> exportComprehensiveReport(context, request);
            default -> throw new IllegalArgumentException("Invalid report type: " + reportType);
        };

        // Convert to PDF if requested
        if ("PDF".equals(format)) {
            return convertCsvToPdf(csvData, reportType, context);
        }

        return csvData;
    }

    /**
     * Exports enrollment analytics report.
     */
    private byte[] exportEnrollmentReport(DonorContext context, ExportReportRequestDTO request) throws IOException {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PrintWriter writer = new PrintWriter(outputStream);

        // Header
        writer.println("PORTFOLIO-WIDE ENROLLMENT ANALYTICS REPORT");
        writer.println("Generated: " + java.time.LocalDateTime.now().format(
                DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
        writer.println("Generated By: " + context.getFullName() + " (" + context.getEmail() + ")");
        writer.println();

        // Get enrollment analytics
        var analytics = analyticsService.getEnrollmentAnalytics(context);

        writer.println("=== SUMMARY ===");
        writer.println("Total Enrollments," + analytics.getTotalEnrollments());
        writer.println();

        writer.println("=== ENROLLMENT GROWTH (MONTHLY) ===");
        writer.println("Period,Enrollments,Growth %");
        for (var growth : analytics.getEnrollmentGrowth()) {
            writer.println(String.format("%s,%d,%.2f%%",
                    growth.getPeriod(),
                    growth.getEnrollments(),
                    growth.getGrowthPercentage()));
        }
        writer.println();

        writer.println("=== ENROLLMENT BY PARTNER ===");
        writer.println("Partner ID,Partner Name,Total Enrollments,Percentage");
        for (var partner : analytics.getEnrollmentByPartner()) {
            writer.println(String.format("%s,%s,%d,%.2f%%",
                    escapeCsv(partner.getPartnerId()),
                    escapeCsv(partner.getPartnerName()),
                    partner.getTotalEnrollments(),
                    partner.getPercentage()));
        }
        writer.println();

        writer.println("=== ENROLLMENT BY PROGRAM ===");
        writer.println("Program ID,Program Name,Partner ID,Partner Name,Total Enrollments,Percentage");
        for (var program : analytics.getEnrollmentByProgram()) {
            writer.println(String.format("%s,%s,%s,%s,%d,%.2f%%",
                    program.getProgramId(),
                    escapeCsv(program.getProgramName()),
                    escapeCsv(program.getPartnerId()),
                    escapeCsv(program.getPartnerName()),
                    program.getTotalEnrollments(),
                    program.getPercentage()));
        }

        writer.flush();
        writer.close();
        return outputStream.toByteArray();
    }

    /**
     * Exports employment analytics report.
     */
    private byte[] exportEmploymentReport(DonorContext context, ExportReportRequestDTO request) throws IOException {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PrintWriter writer = new PrintWriter(outputStream);

        // Header
        writer.println("PORTFOLIO-WIDE EMPLOYMENT ANALYTICS REPORT");
        writer.println("Generated: " + java.time.LocalDateTime.now().format(
                DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
        writer.println("Generated By: " + context.getFullName() + " (" + context.getEmail() + ")");
        writer.println();

        // Get employment analytics
        var analytics = analyticsService.getEmploymentAnalytics(context);

        writer.println("=== SUMMARY ===");
        writer.println(String.format("Overall Employment Rate,%.2f%%", analytics.getOverallEmploymentRate()));
        writer.println("Total Completed Enrollments," + analytics.getTotalCompletedEnrollments());
        writer.println("Total Employed," + analytics.getTotalEmployed());
        writer.println();

        writer.println("=== EMPLOYMENT BY PARTNER ===");
        writer.println("Partner ID,Partner Name,Completed Enrollments,Employed,Employment Rate %");
        for (var partner : analytics.getEmploymentByPartner()) {
            writer.println(String.format("%s,%s,%d,%d,%.2f%%",
                    escapeCsv(partner.getPartnerId()),
                    escapeCsv(partner.getPartnerName()),
                    partner.getTotalCompletedEnrollments(),
                    partner.getTotalEmployed(),
                    partner.getEmploymentRate()));
        }
        writer.println();

        writer.println("=== EMPLOYMENT BY COHORT ===");
        writer.println("Cohort ID,Cohort Name,Program Name,Partner Name,Completed Enrollments,Employed,Employment Rate %");
        for (var cohort : analytics.getEmploymentByCohort()) {
            writer.println(String.format("%s,%s,%s,%s,%d,%d,%.2f%%",
                    cohort.getCohortId(),
                    escapeCsv(cohort.getCohortName()),
                    escapeCsv(cohort.getProgramName()),
                    escapeCsv(cohort.getPartnerName()),
                    cohort.getTotalCompletedEnrollments(),
                    cohort.getTotalEmployed(),
                    cohort.getEmploymentRate()));
        }
        writer.println();

        writer.println("=== INTERNSHIP CONVERSION ===");
        writer.println(String.format("Total Completed Internships,%d", analytics.getInternshipConversion().getTotalCompletedInternships()));
        writer.println(String.format("Converted to Employment,%d", analytics.getInternshipConversion().getInternshipsConvertedToEmployment()));
        writer.println(String.format("Conversion Rate,%.2f%%", analytics.getInternshipConversion().getConversionRate()));

        writer.flush();
        writer.close();
        return outputStream.toByteArray();
    }

    /**
     * Exports demographic analytics report.
     */
    private byte[] exportDemographicReport(DonorContext context, ExportReportRequestDTO request) throws IOException {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PrintWriter writer = new PrintWriter(outputStream);

        // Header
        writer.println("PORTFOLIO-WIDE DEMOGRAPHIC & INCLUSION ANALYTICS REPORT");
        writer.println("Generated: " + java.time.LocalDateTime.now().format(
                DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
        writer.println("Generated By: " + context.getFullName() + " (" + context.getEmail() + ")");
        writer.println();

        // Get demographic analytics
        var analytics = analyticsService.getDemographicAnalytics(context);

        writer.println("=== SUMMARY ===");
        writer.println("Total Participants," + analytics.getTotalParticipants());
        writer.println();

        writer.println("=== GENDER BREAKDOWN ===");
        writer.println("Gender,Count,Percentage");
        for (var gender : analytics.getGenderBreakdown()) {
            writer.println(String.format("%s,%d,%.2f%%",
                    gender.getGender(),
                    gender.getCount(),
                    gender.getPercentage()));
        }
        writer.println();

        writer.println("=== DISABILITY STATUS BREAKDOWN ===");
        writer.println("Disability Status,Count,Percentage");
        for (var disability : analytics.getDisabilityBreakdown()) {
            writer.println(String.format("%s,%d,%.2f%%",
                    disability.getDisabilityStatus(),
                    disability.getCount(),
                    disability.getPercentage()));
        }
        writer.println();

        writer.println("=== EDUCATION LEVEL BREAKDOWN ===");
        writer.println("Education Level,Count,Percentage");
        for (var education : analytics.getEducationBreakdown()) {
            writer.println(String.format("%s,%d,%.2f%%",
                    escapeCsv(education.getEducationLevel()),
                    education.getCount(),
                    education.getPercentage()));
        }

        writer.flush();
        writer.close();
        return outputStream.toByteArray();
    }

    /**
     * Exports comprehensive report (all analytics).
     */
    private byte[] exportComprehensiveReport(DonorContext context, ExportReportRequestDTO request) throws IOException {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        PrintWriter writer = new PrintWriter(outputStream);

        writer.println("=== PORTFOLIO-WIDE COMPREHENSIVE ANALYTICS REPORT ===");
        writer.println("Generated: " + java.time.LocalDateTime.now().format(
                DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
        writer.println("Generated By: " + context.getFullName() + " (" + context.getEmail() + ")");
        writer.println();

        // Enrollment section
        writer.println("=== ENROLLMENT ANALYTICS ===");
        byte[] enrollmentData = exportEnrollmentReport(context, request);
        String enrollmentStr = new String(enrollmentData);
        // Skip header lines
        String[] enrollmentLines = enrollmentStr.split("\n");
        boolean skipHeader = true;
        for (String line : enrollmentLines) {
            if (skipHeader && line.contains("===")) {
                skipHeader = false;
                continue;
            }
            if (!skipHeader) {
                writer.println(line);
            }
        }
        writer.println();

        // Employment section
        writer.println("=== EMPLOYMENT ANALYTICS ===");
        byte[] employmentData = exportEmploymentReport(context, request);
        String employmentStr = new String(employmentData);
        String[] employmentLines = employmentStr.split("\n");
        skipHeader = true;
        for (String line : employmentLines) {
            if (skipHeader && line.contains("===")) {
                skipHeader = false;
                continue;
            }
            if (!skipHeader) {
                writer.println(line);
            }
        }
        writer.println();

        // Demographic section
        writer.println("=== DEMOGRAPHIC ANALYTICS ===");
        byte[] demographicData = exportDemographicReport(context, request);
        String demographicStr = new String(demographicData);
        String[] demographicLines = demographicStr.split("\n");
        skipHeader = true;
        for (String line : demographicLines) {
            if (skipHeader && line.contains("===")) {
                skipHeader = false;
                continue;
            }
            if (!skipHeader) {
                writer.println(line);
            }
        }

        writer.flush();
        writer.close();
        return outputStream.toByteArray();
    }

    /**
     * Escapes CSV special characters.
     */
    private String escapeCsv(String value) {
        if (value == null) return "";
        if (value.contains(",") || value.contains("\"") || value.contains("\n")) {
            return "\"" + value.replace("\"", "\"\"") + "\"";
        }
        return value;
    }

    /**
     * Converts CSV data to PDF format using Apache PDFBox.
     */
    private byte[] convertCsvToPdf(byte[] csvData, String reportType, DonorContext context) throws IOException {
        try {
            org.apache.pdfbox.pdmodel.PDDocument document = new org.apache.pdfbox.pdmodel.PDDocument();
            org.apache.pdfbox.pdmodel.PDPage page = new org.apache.pdfbox.pdmodel.PDPage(org.apache.pdfbox.pdmodel.common.PDRectangle.A4);
            document.addPage(page);

            org.apache.pdfbox.pdmodel.PDPageContentStream contentStream = 
                    new org.apache.pdfbox.pdmodel.PDPageContentStream(document, page);

            // Set up fonts
            org.apache.pdfbox.pdmodel.font.PDType1Font titleFont = org.apache.pdfbox.pdmodel.font.PDType1Font.HELVETICA_BOLD;
            org.apache.pdfbox.pdmodel.font.PDType1Font headerFont = org.apache.pdfbox.pdmodel.font.PDType1Font.HELVETICA_BOLD;
            org.apache.pdfbox.pdmodel.font.PDType1Font bodyFont = org.apache.pdfbox.pdmodel.font.PDType1Font.HELVETICA;

            float margin = 50;
            float yPosition = page.getMediaBox().getHeight() - margin;
            float lineHeight = 14;
            float fontSize = 10;

            // Write title with branding
            contentStream.beginText();
            contentStream.setFont(titleFont, 16);
            contentStream.newLineAtOffset(margin, yPosition);
            contentStream.showText("DSE M&E Platform - " + reportType + " Report");
            contentStream.endText();
            yPosition -= lineHeight * 2;

            // Write metadata
            contentStream.beginText();
            contentStream.setFont(bodyFont, fontSize);
            contentStream.newLineAtOffset(margin, yPosition);
            contentStream.showText("Generated: " + java.time.LocalDateTime.now().format(
                    DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")));
            contentStream.endText();
            yPosition -= lineHeight;

            contentStream.beginText();
            contentStream.setFont(bodyFont, fontSize);
            contentStream.newLineAtOffset(margin, yPosition);
            contentStream.showText("Generated By: " + context.getFullName() + " (" + context.getEmail() + ")");
            contentStream.endText();
            yPosition -= lineHeight * 2;

            // Parse CSV and write to PDF
            String csvString = new String(csvData);
            String[] lines = csvString.split("\n");
            
            boolean isHeader = true;
            for (String line : lines) {
                if (line.trim().isEmpty() || line.startsWith("===")) {
                    // Skip empty lines and section headers
                    continue;
                }

                if (yPosition < margin + lineHeight) {
                    // Create new page
                    contentStream.close();
                    page = new org.apache.pdfbox.pdmodel.PDPage(org.apache.pdfbox.pdmodel.common.PDRectangle.A4);
                    document.addPage(page);
                    contentStream = new org.apache.pdfbox.pdmodel.PDPageContentStream(document, page);
                    yPosition = page.getMediaBox().getHeight() - margin;
                }

                // Truncate line if too long for PDF
                String displayLine = line.length() > 100 ? line.substring(0, 97) + "..." : line;
                
                contentStream.beginText();
                contentStream.setFont(isHeader ? headerFont : bodyFont, fontSize);
                contentStream.newLineAtOffset(margin, yPosition);
                contentStream.showText(displayLine.replace(",", " | ")); // Replace commas with pipes for readability
                contentStream.endText();
                yPosition -= lineHeight;
                
                isHeader = false;
            }

            contentStream.close();

            // Convert to byte array
            ByteArrayOutputStream pdfOutputStream = new ByteArrayOutputStream();
            document.save(pdfOutputStream);
            document.close();

            return pdfOutputStream.toByteArray();
        } catch (Exception e) {
            log.error("Error converting CSV to PDF: {}", e.getMessage(), e);
            throw new IOException("Failed to generate PDF: " + e.getMessage(), e);
        }
    }

    /**
     * Creates a report snapshot for scheduled reports.
     * 
     * @param context DONOR context
     * @param reportType Report type
     * @param periodStart Period start date
     * @param periodEnd Period end date
     * @param reportData Report data (CSV format)
     * @param format File format (CSV or PDF)
     * @return Created report snapshot
     */
    @Transactional
    public ReportSnapshot createReportSnapshot(
            DonorContext context,
            String reportType,
            LocalDate periodStart,
            LocalDate periodEnd,
            byte[] reportData,
            String format
    ) {
        // For DONOR reports, we don't associate with a specific partner
        // Use a default "PORTFOLIO" partner or create a system partner
        Partner portfolioPartner = partnerRepository.findById("PORTFOLIO")
                .orElseGet(() -> {
                    // Create a system partner for portfolio-wide reports
                    Partner partner = new Partner();
                    partner.setPartnerId("PORTFOLIO");
                    partner.setPartnerName("Portfolio-Wide Reports");
                    partner.setIsActive(true);
                    partner.setCreatedAt(Instant.now());
                    partner.setUpdatedAt(Instant.now());
                    return partnerRepository.save(partner);
                });

        ReportSnapshot snapshot = ReportSnapshot.builder()
                .partner(portfolioPartner)
                .reportType(reportType)
                .reportPeriodStart(periodStart)
                .reportPeriodEnd(periodEnd)
                .reportData(new String(reportData))
                .fileFormat(format)
                .fileSizeBytes((long) reportData.length)
                .generatedBy(context.getUser())
                .generatedAt(Instant.now())
                .createdAt(Instant.now())
                .build();

        return reportSnapshotRepository.save(snapshot);
    }
}
